stages:
  - name: Build Application
    steps:
      - runScriptConfig:
          image: statflodevelopment/reactjs
          shellScript: |
            npm install --no-optional
            npm run test
            npm run build
  - name: Publish Image
    steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: eldermael/portfolio-website:latest
  - name: Deploy
    steps:
      - applyYamlConfig:
          path: ./.k8s/app.yaml